export enum themeColors {
    borderLight                     = "#1C0B24",
    bgMainLight                     = "#fff",
    iconColorLight                  = "#00005D",
    textColorLight                  = "#00005D",
    secondaryTextColorLight         = "#979797",
    navigationBackgroundColorLight  = "#fff",
    buttonBgColorLight              = "#E4D8E9",
    secondaryButtonBgColorLight     = "#FDD202",
    buttonColorLight                = "#000D34",
    secondaryButtonColorLight       = "#000D34",
    secondaryButtonHoverColorLight  = "#fff",
    dividerColorLight               = "#979797",
    borderSecondaryLight            = "#A1D0FF",
    navActiveBgColorLight           = "#ededed",
    navInactiveBgColorLight         = "transparent",
    borderDark                      = "#1C0B24",
    bgMainDark                      = "#18191E",
    iconColorDark                   = "#148AFF",
    textColorDark                   = "#E4D8E9",
    buttonBgColorDark               = "#E4D8E9",
    buttonColorDark                 = "#E4D8E9",
    secondaryButtonBgColorDark      = "#FDD202",
    secondaryButtonColorDark        = "#FDD202",
    secondaryButtonHoverColorDark   = "#fff",
    secondaryTextColorDark          = "#979797",
    navigationBackgroundColorDark   = "#18191E",
    dividerColorDark                = "rgba(65,160,255,0.41)",
    borderSecondaryDark             = "#A1D0FF",
    navActiveBgColorDark            = "#2211aa",
    navInactiveBgColorDark          = "transparent",
}

export enum styleCommonUtils {
    boxShadowLight  = "0, 5px, 12px, 4px, rgba(0,0,93,0.24)",
    boxShadowDark   = "3px, 3px, 15px, 4px, rgba(65,160,255,0.41)",
}