export enum themeColors {
    borderLight                     = "#1C0B24",
    bgMainLight                     = "#fff",
    cardBgLight                     = "#fff",
    iconColorLight                  = "#00005D",
    textColorLight                  = "#00005D",
    secondaryTextColorLight         = "#979797",
    navigationBackgroundColorLight  = "#fff",
    sideBarBackgroundColorLight     = "#148AFF",
    sideBarTextColorLight           = "#fff",
    buttonBgColorLight              = "#148AFF",
    secondaryButtonBgColorLight     = "#FDD202",
    buttonColorLight                = "#fff",
    secondaryButtonColorLight       = "#000D34",
    secondaryButtonHoverColorLight  = "#fff",
    dividerColorLight               = "#979797",
    borderSecondaryLight            = "#A1D0FF",
    navActiveBgColorLight           = "#1368dd",
    navInactiveBgColorLight         = "transparent",
    borderDark                      = "#1C0B24",
    bgMainDark                      = "#18191E",
    cardBgDark                      = "transparent",
    iconColorDark                   = "#148AFF",
    textColorDark                   = "#fff",
    buttonBgColorDark               = "#148AFF",
    buttonColorDark                 = "#fff",
    secondaryButtonBgColorDark      = "#FDD202",
    secondaryButtonColorDark        = "#FDD202",
    secondaryButtonHoverColorDark   = "#fff",
    secondaryTextColorDark          = "#979797",
    navigationBackgroundColorDark   = "#18191E",
    sideBarBackgroundColorDark      = "#121923",
    sideBarTextColorDark            = "#fff",
    dividerColorDark                = "rgba(65,160,255,0.41)",
    borderSecondaryDark             = "#A1D0FF",
    navActiveBgColorDark            = "#2211aa",
    navInactiveBgColorDark          = "transparent",
}

export enum styleCommonUtils {
    boxShadowLight  = "0, 5px, 12px, 4px, rgba(0,0,93,0.24)",
    boxShadowDark   = "3px, 3px, 15px, 4px, rgba(65,160,255,0.41)",
    paddingXs  = "0.25rem",
    paddingSm  = "0.4rem",
    paddingMd  = "0.7rem",
    paddingLg  = "1.2rem",
    paddingXl  = "1.5rem",
}